### ISSUE TITLE
Stream build errors to problems view follow up

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#122]
During the build, we create problems and markers as we parse bazel output, asynchronously.  Our goal is to show errors as soon as they are available, instead of having to wait for the bazel invocation to complete. However, the problems view isn't actually updated until BazelBuilder's build method completes, which defeats what we are trying to do.  It appears that the problems view is locked for the duration of the build. Fix this so that the problems view is updated while the bazel build is progressing.

This is where we attempt to update the problems view asynchronously: https://github.com/salesforce/bazel-eclipse/blob/c0b15615953ecdbaec4405074268ae20fb6c1537/plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelErrorStreamObserver.java#L96

Also see issue #41 for more background.

**Comment by plaird** [comment]
@dylanShark  and @simontoens took a swing at this (thanks!), and found that this isn't a straightforward feature. There is resource locking inside of Eclipse that prevented the streamed markers to the Problems view. Closing this, as we probably wouldn't prioritize this for a very long time.
