### ISSUE TITLE
 Error importing the Bazel workspace. Details: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by omathias** [salesforce/bazel-eclipse#142]
This is the same java-tutorial project from Bazel and its WORKSPACE file which is empty
Using Eclipse version - Version: 2019-12 (4.14.0)

**Comment by plaird** [comment]
OK, thanks for reporting. We plan to do a release next week of current state (1.2.0), and then a minor after (1.2.5) to mostly fix import performance. We can add this to 1.2.5.

**Comment by omathias** [comment]
@plaird  When can I expect 1.2.5 to be released

**Comment by plaird** [comment]
I had a chance to look at this specific use case tonight. I am happy to say that the current version of BEF (soon to be 1.2.0) does not fail as reported. However, there are problems. The roadmap section of our README:
https://github.com/salesforce/bazel-eclipse#bef-status-and-roadmap

links to the following page, which covers file layout conventions for Bazel workspaces that are currently required by BEF:
https://github.com/salesforce/bazel-eclipse/blob/master/docs/conforming_java_packages.md

The rationale is explained in the doc, but generally Bazel has a lot of flexibility that will be difficult to map into the existing Maven inspired Java tooling for Eclipse (JDT). For example, in JDT you have just two classpaths for a project (main and test) whereas in Bazel a single package can have unlimited distinct classpaths (one per java target in a BUILD file). In most cases, I think we will be able to find solutions and workarounds, but this will take some effort.

The java-tutorial project violates a few of our current file layout conventions:
- the package is not rooted directly in the workspace directory (i.e. beside the WORKSPACE file) but in a subdirectory (the top-level BUILD file violates this)
- contains a single top-level module BUILD file (the *cmdline* package violates this)

It is easy to resolve the first issue, by issuing these commands from the java-tutorial directory:
```
$ mkdir tutorial
$ mv BUILD tutorial
$ mv src tutorial
```
and then fixing up a few references in the cmdline build file. Be sure that ```bazel build //...``` is successful prior to the import.

During import, you will also need to uncheck the cmdline package, as it violates convention 2 above. To fix this, you will need to migrate that BUILD file rules into the //tutorial/BUILD file.

Most of the work you would need to import java-tutorial as-is is covered by this issue:  #24 
We are further out than 1.2.x for tackling that. There are multiple ways to approach it, none of which will be easy.

**Comment by plaird** [comment]
I will close this now, as the work to import non-conforming packages is already captured in other issues, noted above.
