### ISSUE TITLE
Deadlocks during runs of BazelProblemMarkerManager 

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#150]
After about 5 minutes after import of a Bazel workspace, and after I had run a test, I tried to remove a breakpoint in one of my tests. It hung the IDE. I captured some threads, though I wish I would have done a full thread dump. I have tried to repro and cannot.

The suspicious thread for BEF is BazelProblemMarkerManager.

**Comment by plaird** [comment]
A couple of the threads
<img width="913" alt="deadlock_mainthread" src="https://user-images.githubusercontent.com/921358/86819528-01946400-c045-11ea-8f2b-2f1f6cae55f9.png">
<img width="880" alt="deadlock_problemsthread" src="https://user-images.githubusercontent.com/921358/86819537-03f6be00-c045-11ea-9192-d3e658c88877.png">

**Comment by plaird** [comment]
I hit another case, not related to breakpoints. This time I captured the full stack.

[deadlock_stack.txt](https://github.com/salesforce/bazel-eclipse/files/4886307/deadlock_stack.txt)

**Comment by simontoens** [comment]
Lets revert the work done to make error processing async.  It is not really needed.

**Comment by plaird** [comment]
I have been running with this today, and haven't seen a deadlock. I also think your explanation sounds like the probable cause, so I will close this as fixed. If we see it again, will reopen. Thanks @simontoens for the fix.
