### ISSUE TITLE
Switch to BEP for collecting compiler warnings and errors for the Eclipse Problems View

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#155]
Currently, we are parsing the build output for identifying errors and warnings for the Eclipse Problems View. See BazelOutputParser.

There is a design doc and PR to improve Bazel Event Protocol to carry this information:

- [Structured Compiler Diagnostics](https://docs.google.com/document/d/1KCQMvUMNVUBDyDmZJ1DB80tf21MVQdyWYS0Y9D_P0as/edit#heading=h.5mcn15i0e1ch)
- [Diagnostic PR to Bazel](https://github.com/bazelbuild/bazel/pull/11766)

We will need to continue to support our current output-parsing for a long time (this BEP feature will go into Bazel 4.x?) in order to support older Bazel versions. But it would be nice to use BEP where possible, as that is the intended hook for IDEs.

**Comment by jastice** [comment]
Note that the motivation for the structured compiler diagnostics is to be able to support the [Build Server Protocol](https://build-server-protocol.github.io/) better, currently implemented via https://github.com/andrefmrocha/bazel-bsp

**Comment by plaird** [comment]
@jastice thanks for the context, it looks like the feature will be very helpful to us (and other IDE integrators).
