### ISSUE TITLE
Publish on Eclipse Marketplace

### ISSUE THREAD

**Issue by mickaelistria** [salesforce/bazel-eclipse#162]
I was looking at plugins allowing to work in Bazel in Eclipse IDE, and didn't find anything on marketplace.eclipse.org.
Eclipse Marketplace is where many users look for plugins, it would be beneficial to both IDE and Bazel plugin if this interesting  plugin was visible and installable from Eclipse Marketplace.

**Comment by mickaelistria** [comment]
#163 seems to be a requirement.

**Comment by plaird** [comment]
@guw fyi this is one more packaging todo on the backlog. I can look into it unless you have prior knowledge about how to do it.

**Comment by guw** [comment]
That's not really packaging. It's more admin type of work. Because we have the update site now all we need is to create a listing on http://marketplace.eclipse.org/ which references our update site. The listing needs to be updated with every new version we release.

**Comment by plaird** [comment]
https://marketplace.eclipse.org/content/bazel-eclipse-feature has been submitted for moderation.

**Comment by plaird** [comment]
Boom! We are live: https://marketplace.eclipse.org/content/bazel-eclipse-feature

Thanks @mickaelistria for the suggestion!
