### ISSUE TITLE
Publish an unzipped p2 repository on some available URL

### ISSUE THREAD

**Issue by mickaelistria** [salesforce/bazel-eclipse#163]
(related to #162)
In order to ease installation and to make it possible to expose the plugin on Eclipse Marketplace, the project should publish an unzipped p2 repository at some location.
GitHub sites could for example be used to automatically push latest release to the GitHub site. If the URL doesn't change, that would also allow users to be prompted automatically to update new release when its published.

**Comment by plaird** [comment]
This StackOverflow page has some ideas for how to do it:
https://stackoverflow.com/questions/2801567/is-it-possible-to-host-an-eclipse-update-site-on-github

with this concrete example:
https://github.com/donkirkby/live-py-plugin/tree/master/docs/update

**Comment by guw** [comment]
@plaird Taking over if you don't mind.

**Comment by plaird** [comment]
Thanks!

**Comment by guw** [comment]
Update site is at https://salesforce.github.io/bazel-eclipse/

**Comment by plaird** [comment]
Verified that I could install BEF from the update site. However, there is something broken with the Bazel aspects when run from the updatesite/zip file. The Bazel classpath is failing during computation. This works fine when run from Inner Eclipse, so it is something going on with the way the updatesite is laid out. I will look into it more...

**Comment by plaird** [comment]
The aspect issue was fixed in PR #220. I will do a test release soon and verify the update site feature.

**Comment by plaird** [comment]
Thanks @guw for all the work! I made some small updates to the release workflow, and updated the our dev docs for how to push a new release. I ran a patch release today to make sure it all works.
