### ISSUE TITLE
Modernize and improve BEF project import error handling

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#193]
We have some error handling in place for failed project imports, but it doesn't work very well and it seems brittle. We need to re-visit how we can better handle failed imports.

**Comment by guw** [comment]
@plaird Do you have some ideas in mind? I am running into this currently. I get an error reported for a random closed project in my workspace, which is not added properly to the Eclipse error log.

**Comment by plaird** [comment]
No I don't have anything specific in mind for this. I just fixed a class of these errors in 1.5: reimporting a Bazel workspace, delete those projects, and import again. While doing that I made the error dialog popup a little better. Did you get a nice error modal dialog for this case?
