### ISSUE TITLE
Do not require test deploy jars for JUnit integration

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#205]
Our current JUnit integration relies on test _deploy jars. These are slow to build, slowing down every "bazel build" invocation.  Review our JUnit integration to see if we can get rid of this requirement.
Once we no longer need to build these jars, we can switch the default wildcard target we use from "\*" to "all" here ("all" does not include _deploy jars): https://github.com/salesforce/bazel-eclipse/blob/7850e5b79ac2dc2f941fb4be796429fef87f26c5/bzl-java-sdk/src/main/java/com/salesforce/bazel/sdk/util/BazelConstants.java#L62

**Comment by plaird** [comment]
This was solved by #18. Closing...
