### ISSUE TITLE
Solidify and document Eclipse target platform

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#250]
Out of the blue, our target platform disappeared from the eclipse.org and we had to make this update:

https://github.com/salesforce/bazel-eclipse/pull/249/files

Some issues:
- Can't we point to some LTS version of Eclipse; I would actually prefer not to use latest bits, we should target an older version of Eclipse since nothing we are doing with JDT should require anything new
- PR 249 broke the BEF build on Windows, there is more work to do there
- We need to have a daily CI build to catch these types of issues

**Comment by plaird-alt** [comment]
The Windows build error that happens now is here:

https://gist.github.com/plaird-alt/2d7e383387108cedf6fe38bb5a63af5a

Short version:
```
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.122.200.v20210506-1640
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 41 more
```

**Comment by guw** [comment]
PR #249 addressed point 1 (switching to release build). The windows issue needs to be investigated. That shouldn't happen. I suspect it's something off with the test/Tycho configuration.

**Comment by guw** [comment]
@plaird @plaird-alt I think I found the Windows issue. The target platform is not configured to allow Windows:
https://github.com/salesforce/bazel-eclipse/blob/44bd9074d4f43806600b4ab21787a7a688673f0f/releng/mavenparent/pom.xml#L234-L250

There is a duplicate Mac entry. This should be converted into one for Windows.

**Comment by plaird** [comment]
Daily CI build is implemented for all platforms.
