### ISSUE TITLE
Harmonize BEF repo with bazel-ls-eclipse repo

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#256]
As per #237 our roadmap is to merge the [bazel-ls-eclipse language server](https://github.com/salesforce/bazel-ls-eclipse) repository into the BEF repository. This is because they are related projects and we feel that the two Salesforce teams will get benefit from being in the same repository.

We need to do the following:
- increase test coverage to bazel-ls-eclipse because we will be doing major reconstruction work to bring it up to date with the latest SDK
- cherry pick commits from bazel-ls-eclipse to the BEF/SDK repos; they have some nice fixes that we need to bring in
- bazel-ls-eclipse has taken a much newer version of the IJ Aspect and BEF is far behind. It is expected that porting the bazel-ls-eclipse Aspect changes to BEF/SDK to be somewhat difficult
- reverse the flow and update bazel-ls-eclipse to the latest (merged) version of the SDK. This will take some work because I have made a lot of refactorings in the SDK

**Comment by plaird** [comment]
@PMitrafanau this is the work item I will use to bring language server updates into BEF/SDK. 
@guw  FYI

**Comment by plaird** [comment]
Given the changes to Aspects being potentially disruptive, I decided to finish the 1.4 BEF release without this. I just finished #36 (Windows support), and have one small bug fix #180 to finish. Then I will work on the bazel-ls-eclipse port.

**Comment by plaird** [comment]
This work is done, except for the aspect. In most cases I was able to bring in the changes directly, but in some cases both projects refactored the code and so I had to visually compare and make sure any fixes were brought back into the SDK.  

@PMitrafanau do you remember the motivation to sync the aspect with the IJ project? 

I have been looking at the updated Aspect, and they make it a lot more complicated because the IJ project is supporting a lot more languages than Java. For BEF, it is my 2022 goal to support other JVM langs, and then non-JVM langs (C, Go) in the long term. 

I am just wondering if we can push this work out until we need it, or whether there was something specific you wanted from this change. I would prefer to have the much simpler Java aspect that we have now. I think LS is just targeting Java projects right now?

**Comment by guw** [comment]
@plaird I can answer this one. The aspects update was needed in order to address a significant performance issue with larger projects. The new aspects run an order of magnitude faster and allow importing a large monolith we use internally. There is a [sample large project here](https://github.com/salesforce/bazel-ls-demo-project/tree/master/large).

**Comment by plaird** [comment]
The new aspect is a big change, but I am almost done. The remaining thing to figure out is how to get the list of json files that were generated by the aspect. In the old aspect, that was written to output. The new one doesn't seem to do it.

**Comment by plaird** [comment]
PR #269 is the major refactor to use the new IJ aspect. I will do another round of cleanup but that work is otherwise complete.

With that, we have all changes from LS that we want, ported to BEF/SDK. The final step will be to port the latest SDK code base to LS. Which will be a major rework of LS.

@PMitrafanau @guw

**Comment by plaird** [comment]
Cleanup work is now complete, and I also tested on Windows and it was successful. I have cut an interim release of BEF if you are interested in trying it. Release candidate update site:  http://opensource.salesforce.com/bazel-eclipse/update-site-release-candidate

**Comment by plaird** [comment]
@PMitrafanau @guw I worked on and sent the reverse PR to the LS repo: https://github.com/salesforce/bazel-ls-eclipse/pull/110

**Comment by plaird** [comment]
@AlexeiShmidman finished this work item in #292. Closing...
