### ISSUE TITLE
Bazel classpath container does not mark test jars as only available to test source files

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#29]
Currently a src/main/java class can reference org.junit.Assert, for example.
The reason is the classpath container is not adding the TEST attribute to dep libs that come in via java_test targets in the project.

This is not a simple fix beause currently the classpath container is taking the union of all targets in the BUILD file (using the :* wildcard) and then handling that off to the Bazel command line to generate all aspect json files at once for all the BUILD targets. That command returns a number of aspect json files, but we cannot distinguish which ones were generated due to java_test targets and which ones are from java_library and java_binary targets.

We will need to refactor the way we run the Aspect command line. We need to generate the list of Bazel targets in a BUILD file, and then individually ask for each set of dep aspects per target. This will slow things down.

**Repro:**
- in any main source jar, add an import to org.junit.Assert which should not resolve
- open Build Path UI view
- click on Libraries tab, open the Bazel Classpath Container node
- open the junit.jar node
- see that the "Visible only for test sources" is marked no, it should be yes

**Comment by plaird** [comment]
The more I think about this, the more I think this will trigger a reimplementation of the classpath container. The Aspect approach got us so far, but I think switching to a Bazel query approach to compute the target metadata is the way of the future. In addition to the complexities seen on the first try of this ticket, in trying to add Selenium support #47 I found that the Aspect would need to grow even more complex.

**Comment by guw** [comment]
@plaird  Bazel doesn't have the notion of classpath scope like Maven does. How do you plan on identifying "test" stuff?

**Comment by plaird** [comment]
@guw Maven also has strong directory layout conventions (src/main/java, src/test/java).

JDT was built assuming that every project needs just two classpaths - main and test. This made sense for simple java projects and maven projects. But as you point out, every Bazel package can have an arbitrary number of classpaths (one per java rule) so it does not fit the JDT model.

We currently don't plan to crack open JDT and make changes for BEF. So we declare additional constraints in documentation on Bazel packages such that they can be mapped into JDT. 
https://github.com/salesforce/bazel-eclipse/blob/master/docs/conforming_java_packages.md

This issue #29 is focused on merging classpath from java_test rules and specifying that as the JDT test classpath. The output from the Aspect has this information. I took a crack at it, and was almost there, but there was a lot of refactoring of the current BEF code base required. But it is achievable.

The bigger issue of supporting N classpaths per Eclipse project/Bazel package is discussed in issue #23 and I am pretty pessimistic of ever overcoming that.

FWIW, the IJ-Bazel plugin team is having similar (actually, bigger) issues. They have one classpath for the entire Bazel workspace. https://github.com/bazelbuild/intellij/issues/179

**Comment by plaird** [comment]
This branch contains an old attempt at this. It mostly worked but was a lot of refactoring.

https://github.com/salesforce/bazel-eclipse/tree/plaird/main_test_cp_split

**Comment by plaird** [comment]
Most of the refactoring mentioned in the previous comment has now been merged into master as #100 . With that in place the PR to implement the test classpath will be smaller.

**Comment by plaird** [comment]
BazelClasspathContainer has been updated in #104 to be add test jars only to the JDT test classpath.
