### ISSUE TITLE
Implement independent releases for BEF and BJLS

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#350]
We have two different workflows for BEF and BJLS for releasing, which is a good start.

But right now both workflows release both BEF and BJLS to their distinct update sites. What we really want is BEF and its required plugins released to the BEF update site. And the BJLS and its plugins released to the BJLS update site.

**Comment by guw** [comment]
@plaird I'm against that. It introduces complexity. We should instead produce BJLS together with BEF and don't even use separate workflows. I'd like to see this as a true mono-repo. Any change we do to BEF should also be available to the BJLS and the BJLS specific unit tests should run as well. Same for the other case.

**Comment by vorburger** [comment]
+1 to simply moving to a monorepo and merging this and https://github.com/salesforce/bazel-vscode ...

Learning via https://github.com/salesforce/bazel-vscode/issues/23 that `bazel-vscode` requires this (and is comparatively small), why not just move the content of that repo into a sub-directory of this repo, perhaps named (see also https://github.com/salesforce/bazel-vscode/issues/24) something like `vscode-java/`, or even just `vscode/` if you consider it not JDT specific?  (You COULD even do this kind of move with preserving git log history; I've done this before.)

Just seems easier for your to manage.

**Comment by plaird** [comment]
Yes, as far as the vscode work goes, I think Gunnar's team will be bringing that all together.

The original intent of the Issue was to envision a scenario in which we released Bazel Eclipse for a UI bug fix, which would then trigger a BJLS release with probably no code changes. That could be confusing to the BJLS community. But, at this point that particular case is not a pressing issue so we can ignore it for now.
