### ISSUE TITLE
Refresh Bazel Classpath Containers when a BUILD file or Projects change

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#39]
As a BEF user
I would like to change a BUILD file with updated dependencies
Such that the classpath containers in the Eclipse projects generated by BEF are updated

As a BEF user
I would like to import a few more projects from my Bazel workspace into my existing Eclipse workspace
Such that the classpath containers in the existing Eclipse projects generated by BEF are updated
Such that project references are correct

**Background:**
Currently we do a big cycle of running Aspects when projects are imported
We need to flush the Aspect cache and flush the computed classpath of the affected Eclipse projects when a user changes a BUILD file, or when a user imports more projects.

**Comment by plaird** [comment]
I disabled this logic because when this solution was enabled, another issue #145 with this solution was causing unacceptable performance impacts on the user.

#145 has now been resolved, so we should try enabling this feature again.
https://github.com/salesforce/bazel-eclipse/blob/master/plugin-core/src/main/java/com/salesforce/bazel/eclipse/builder/BazelBuilder.java#L143

**Comment by simontoens** [comment]
I am looking at this now.

**Comment by plaird** [comment]
I verified this, and it works. Thanks @simontoens!
