### ISSUE TITLE
Stream build results as they occur into the Eclipse Problems view

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#41]
As a BEF user with some packages that take a long time to build
I would like to see build errors/warnings populate the Eclipse Problems view as they happen
Such that I don't have to wait for my packages with long build times to complete before seeing them

**Comment by plaird** [comment]
To work this ticket, follow these steps:

1. setup your Eclipse SDK as per our dev docs: https://github.com/salesforce/bazel-eclipse/blob/master/docs/dev/dev_guide.md
2. put a breakpoint here: https://github.com/salesforce/bazel-eclipse/blob/master/plugin-libs/plugin-command/src/main/java/com/salesforce/bazel/eclipse/command/shell/ShellCommand.java#L126
3. launch the Inner Eclipse
4. import a small Bazel workspace with java rules
5. the breakpoint will trigger on builds, and you can start iterating from there

**Comment by simontoens** [comment]
Di may look at this.

**Comment by simontoens** [comment]
Di: this repo has example projects you can use to repro: https://github.com/salesforce/bazel-demo

**Comment by simontoens** [comment]
I filed a follow up issue: #122
