### ISSUE TITLE
Implement BEF configuration UI for Bazel launchers

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#42]
As a BEF user
I would like to configure my launcher (java_binary, junit) with more configuration than what is possible today

**Details**
Look at the IntelliJ Bazel launch config UI and the Eclipse Java Launch Config for inspiration. Obvious things that are missing are:

For apps (main methods):
- java arguments (for ex system properties, and argument passed directly to the java executable)
- program arguments
- environment variables?
- bazel flags

For tests
- java args
- bazel flags
- others?

**Comment by simontoens** [comment]
I am making some changes here, so taking this one.

**Comment by simontoens** [comment]
@plaird I added a way to specify arguments a while back.  Obviously we can do more here, but I think what we have now is usable enough.  I am un-assigning myself, but not closing.
