### ISSUE TITLE
Support JDT external annotations files 

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#426]
See the external annotation file (.eea) feature for JDT described here:

https://wiki.eclipse.org/JDT_Core/Null_Analysis/External_Annotations

This is relevant for:
- BEF, such that JDT Java Editor can show these NPE cases as errors (but only if the file is open in the editor)
- Bazel builds that have the Eclipse Java compiler installed as the Java toolchain, such that command line build will emit the error

**Comment by vorburger** [comment]
FYI http://www.lastnpe.org
