### ISSUE TITLE
requires 'osgi.bundle; org.eclipse.jdt.ls.core 0.0.0' but it could not be found

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-eclipse#449]
I'm attempting to follow the https://github.com/salesforce/bazel-eclipse/blob/master/docs/bef/install.md#installing-bazel steps (using the https://opensource.salesforce.com/bazel-eclipse/update-site location, not dragging that button as that somehow doesn't work for me), but am stuck with:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Bazel JDT LS Eclipse Feature 1.5.3.v20221001-0354 (com.salesforce.b2eclipse.jdt.ls.feature.feature.group 1.5.3.v20221001-0354)
  Missing requirement: Bazel JDT LS Plugin 1.5.3.v20221001-0354 (com.salesforce.b2eclipse.jdt.ls 1.5.3.v20221001-0354) requires 'osgi.bundle; org.eclipse.jdt.ls.core 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Bazel JDT LS Eclipse Feature 1.5.3.v20221001-0354 (com.salesforce.b2eclipse.jdt.ls.feature.feature.group 1.5.3.v20221001-0354)
    To: org.eclipse.equinox.p2.iu; com.salesforce.b2eclipse.jdt.ls [1.5.3.v20221001-0354,1.5.3.v20221001-0354]
```

**Comment by vorburger** [comment]
Oh, simply installing using Help > Eclipse Marketplace searching for "Bazel" (and [finding this](https://marketplace.eclipse.org/marketplace-client-intro?mpc_install=5403450)) somehow makes it find that `org.eclipse.jdt.ls.core`.

FYI I faced this with both the _[Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2022-12/r/eclipse-ide-java-developers)_ as wel as the _[Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-12/r/eclipse-ide-enterprise-java-and-web-developers)._

Do you want a PR to update the `install.md` recommending to use Eclipse Marketplace?

@guw

**Comment by guw** [comment]
Looks like the install button is broken because the entry no longer exists.

Did you see this in the install.md:
> Note: BEF users do not need the BJLS Feature. You should leave that unchecked.

I think "do not need" is wrong. It should say "must not".

Can you try with https://opensource.salesforce.com/bazel-eclipse/update-site-release-candidate/?

**Comment by plaird** [comment]
Yes, I always uncheck the JDK LS feature.
