### ISSUE TITLE
Wrong Source Folder (despite src/main/java)

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-eclipse#451]
When I import a very simple sample project https://github.com/vorburger/LearningBazel/tree/develop/java-one (with the version currently on the Eclipse Marketplace, see also #449), then the import "works" (as in, I'm not facing the #450 issue) - BUT the source folder is wrong; it sets `src/main/java/ch/vorburger/learningbazel` instead of just `src/main/java`, and so the `class Main` has _The declared package "ch.vorburger.learniningbazel" does not match the expected package ""_.

**Comment by plaird** [comment]
Wow, this is a basic use case, surprised it is broken. Can you look in your Eclipse log for a log line looking this:

https://github.com/salesforce/bazel-eclipse/blob/master/bundles/com.salesforce.bazel-java-sdk/src/main/java/com/salesforce/bazel/sdk/lang/jvm/MavenProjectStructureStrategy.java#L66

**Comment by plaird** [comment]
I can take this, but it may be a few days for me to get to it.

**Comment by plaird** [comment]
I didn't get back to this...my BEF dev environment is no longer functional. I am not going to have any bandwidth on IDE work for a while so I am taking my name off of this issue. :(
