### ISSUE TITLE
Bazel could not find information about selected project

### ISSUE THREAD

**Issue by peakschris** [salesforce/bazel-eclipse#455]
I'm facing an error getting started with bazel-eclipse. Starting with simple import of a helloworld project. This is eclipse 4.27, latest release of bazel-eclipse, bazel path is set, BAZEL_SH set to valid bash, JAVA_HOME unset, bazel build //... is successful from command line. Windows.

![image](https://user-images.githubusercontent.com/77508021/232228377-4396ce13-4eb2-4a07-9f2c-10af725d9e7f.png)

Any ideas would be much appreciated!

Thanks, Chris

**Comment by plaird** [comment]
Does the console window show anything interesting, like Bazel build errors?
