### ISSUE TITLE
`java_test` targets don't have source files in Eclipse, tests don't show up

### ISSUE THREAD

**Issue by criemen** [salesforce/bazel-eclipse#490]
Hi,

per https://github.com/salesforce/bazel-eclipse/issues/475 I had expected that `java_test` targets work when using `project-per-target`. However, for me, I only get empty eclipse projects for my `java_test` targets, with no sources inside. See https://github.com/criemen/eclipse-repro for an example reproducer.

See this screenshot from the package explorer:
![Image](https://github.com/salesforce/bazel-eclipse/assets/70492/7c25b971-06eb-4062-8a7b-cccee57ae474)

The `project-per-package` strategy would probably work better for my project, but that's buggy for another reason (I'll file a bug shortly, it's not setting up the classpath correctly in our case), so I was forced to look at `project-per-target` first.

**Comment by guw** [comment]
@criemen Not a "fix" to solve the support in IDEs but now at least the problem is surfaced. TL;DR -> the problem is that the targets are located in the workspace root. That causes some trouble in the IDE. If you create a sub-package it should work.
