### ISSUE TITLE
Poor performance in calculating AST trees for massive projects with VSCode

### ISSUE THREAD

**Issue by brian-mcnamara** [salesforce/bazel-eclipse#504]
We're seeing performance issues when the classpath for a bazel project is massive. Things like stepping over breakpoints and class file resolution are taking minutes to complete, and sometimes not even completing. This does seem to likely be cause from some non-performant logic in the vscode language server extensions.

An idea I am proposing is to utilize a partial classpath for bazel import, which would be implemented in a `import_depth` flag which would allow the user to specify the depth of runtime dependencies to include in the Eclipse project structure. Reducing the classpath does resolve all the performance issues we are seeing with VSCode. 
The trade off (currently) is unit tests will not have the required classpath to run, and potentially compile errors (although I have not seen this). I am currently playing around with some ideas to persist the runtime dependencies outside the project model and pass them into the execution (somehow) to work around this.

**Comment by plaird** [comment]
Just happened to come across a pull request to Bazel that is similar. Prune transitive deps for compilation. This is not going to solve your problem, but perhaps some concepts might match.

bazel build <target> --define=experimental_prune_transitive_deps=True

https://github.com/bazelbuild/bazel/pull/19910

**Comment by guw** [comment]
Fixed by #503
