### ISSUE TITLE
BEF root project should always be the first project shown in the project explorer

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#72]
When importing Bazel projects into Eclipse, a special project is created that represents the root of the Bazel workspace (the directory containing Bazel's WORKSPACE file).  This project is called "Bazel Workspace ($directory-name$)".  It should always be the first project shown by the project explorer.  Currently, it looks like the project explorer shows projects in alphabetical order.

**Comment by plaird** [comment]
(note to whomever picks this up) Consider issue #25 (support multiple Bazel workspaces in a single Eclipse workspace) while working on this issue. We will need to extend the ordering logic when we have multiple workspaces.

**Comment by simontoens** [comment]
It seems like we need to define a working set for this: https://stackoverflow.com/questions/19582610/project-order-eclipse-project-explorer-view

@plaird not sure you have any thoughts on this?  Should we always create a working set when projects are initially imported?  There's a related option in the import wizard but I think it isn't used right now?

**Comment by plaird** [comment]
@simontoens since we only import one Bazel workspace into an Eclipse workspace now, I am not sure putting them all in a working set automatically does much. But when we have multiple Bazel workspaces in a single Eclipse workspace, I do see the value in doing that.

**Comment by simontoens** [comment]
@plaird apparently you need them in a woking set to be able to specify an ordering in the project explorer.
