### ISSUE TITLE
Provide a way to specify which targets in a package are built

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#73]
It is possible that a Bazel build contains targets that are:
- slow to build
- not meaningful to an IDE

For example, these could be targets that build docker images or other deployment assemblies, not needed by Eclipse.

Provide a way for users to specify these targets, and exclude them when running "bazel build" commands.  Support exclusion patterns (ie regex), so that targets that follow a common naming pattern can easily be excluded.

**Comment by plaird** [comment]
(note to whomever picks this up) This issue is related to #27 which is an Issue thinking specifically adding UI for project config, with list of targets being one use case. This Issue is focused on the list of targets being configurable, with the UI being part of the impl.

**Comment by plaird** [comment]
We will probably need to do a simple impl first, and then add a more robust solution to the roadmap. The simple impl could be just a set of checkboxes against known targets. Or a regex for include and regex for exclude.

**Comment by plaird** [comment]
Also consider the Project View targets: support in issue #68 when working on this.

**Comment by asmittal** [comment]
This also further complicating the import process. Because when we select the projects while importing, its firing all the targets in those projects. Even the integrations tests. Which are very heavy and have nothing to do with import. 
On selecting projects, it should just show the imported projects in the project window, like any other java project. Building targets should not be connected with import.

**Comment by simontoens** [comment]
@asmittal currently the way import works is that it used a bazel aspect to introspect the build graph.  Getting the aspect to run requires a bazel build, that's the reason all targets are built during import.

**Comment by simontoens** [comment]
@plaird I am now thinking we should only support this via the projectview file, so that there's a single source of truth for configured targets.  What do you think?

**Comment by plaird** [comment]
This may be the concrete solution for most of the issues with Spring Boot development in #213
