### ISSUE TITLE
Bazel Classpath Container references non existing library

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#79]
I see this sometimes when I import/open workspaces. I get an error like:

The container 'Bazel Classpath Container' references non existing library '/private/var/tmp/_bazel_plaird/8fc796cc5b12ab3a49bdc2597c1f16fb/execroot/bazel_demo_simplejava_mvnjar/external/org_hamcrest_hamcrest_core/jar/hamcrest-core-1.3.jar'

The workaround is to close the project that has the error, and reopen it. That eliminates the error. The jar that is being complained about always exists too.

**Comment by simontoens** [comment]
@plaird I am looking at this, so claiming this issue.

**Comment by simontoens** [comment]
I am not sure I actually fixed this, so lets leave this open for a while.

**Comment by plaird** [comment]
We believe this is fixed. I will close, and we can reopen if necessary.
