### ISSUE TITLE
Implement support for ignoring directories with .bazelignore

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#87]
**.bazelignore**
https://docs.bazel.build/versions/master/guide.html#.bazelignore

> You can specify directories within the workspace that you want Bazel to ignore, such as related projects that use other build systems. Place a file called .bazelignore at the root of the workspace and add the directories you want Bazel to ignore, one per line. Entries are relative to the workspace root.

This is the code in the IJ plugin parses it:
https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/projectview/BazelIgnoreParser.java

**Comment by beginningineer** [comment]
hi @plaird ,
just a side note - using Bazel query in BazelProjectImportScanner get this done for free
