### ISSUE TITLE
Implement AutoDeps for BEF

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#91]
We have talked internally about having a feature to automatically track API modules and offer to add the api target to compile_deps, and impl target to runtime_deps. This ticket will track that.

Wix demo'd a similar tool for IJ at BazelCon 2019. If they open source it we can take a look at how they did it. We probably need the user to add a hook into the Bazel workspace to generate a list of class->dep mappings. We need the class to appear even if the package was not imported into BEF. 

Here is a discussion that documents some existing work that may help with this:
https://groups.google.com/u/1/g/bazel-discuss/c/W38EuyqEmvM/m/h0Yi3Zm0AAAJ

**Comment by beginningineer** [comment]
Hi, @plaird 
just viewed Wix demo. I guess "Import class" quickfix may heavy relate on the fact that IJ-Bazel plugin have a sole classpath for the whole workspace (mentioned in https://github.com/salesforce/bazel-eclipse/issues/29#issuecomment-603308294).
In terms of BEF architecture (one classpath per BUILD file) I can't imagine how underlying JDT.Core can get an idea that entered symbol is a valid class name and provide a fix with FQN.

**Comment by plaird** [comment]
@beginningineer good question. I am thinking every Eclipse Bazel project will have second Eclipse classpath container "Bazel AutoDeps Classpath Container" that will contain the candidate list of deps. This will allow the Java Editor of JDT to see everything in the candidate list. The trick will be figuring out when a dep should be added to the Bazel Classpath Container (the BUILD file). Bazel Query can tell us that, but there is some real work there to implement.

**Comment by plaird** [comment]
Progress has been made on this. While the Global Search Classpath feature #161  is experimental and still needs a lot of refinement, I believe it is the first step towards Autodeps.

Details of the Global Search Classpath can be found in #161 and also this doc: https://github.com/salesforce/bazel-eclipse/blob/master/docs/using_the_feature_classpath.md#global-search-classpath

**Comment by plaird** [comment]
This solution can also be expanded to support jars not already in the workspace. This would require calls up to Maven central. The m2eclipse team is implementing such a feature right now in https://github.com/eclipse-m2e/m2e-core/issues/623
