### ISSUE TITLE
java_binary target running through launch configuration cannot be stopped

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#94]
1. Create a new launch configuration for a java_binary target.  This needs to be a long running process.
1. Run the configuration using the green "play" button
1. Use ps to confirm the process is running
1. Switch to the debug view
1. Use the red button from the Debug view to terminate the process - the UI shows the process as terminated
1. Use ps again - the process is still there

(I see the same behavior when debugging instead of just "running")

**Comment by simontoens** [comment]
The problem appears to be that Eclipse kills the outer process ("bazel run"), but not the actual process we care about (the java binary). Proposed fix - instead of calling bazel run, directly call the shell script that bazel run calls, thereby taking bazel out of the picture.

**Comment by plaird** [comment]
I found a description of this behavior here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=67474

(2) If you are using an external tool (ant) to launch your VM, then using the 
terminate button on the associated console only kills the tool, not the 
processes launched by the tool.

(3) Using the terminate button in the debugger actually kills the associated 
VM as this sends a JDI command to exit the VM when it is pushed.

I believe this is the same root issue as noted in #71

**Comment by plaird** [comment]
Issue #71  is still an issue, but this issue is closed. I verified that there is just one running process when debugging a java_binary, and that the red button on the Debug view kills that process.
