### ISSUE TITLE
Review how BEF picks which targets to build

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-eclipse#96]
BEF currently builds the project the change was made in and downstream projects that are imported.  But we should probably also build packages that are not imported?

For example:
A -> B -> C, only A and C imported into Eclipse.  Both A and B use a method in C.  If that method signature is modified, we will only build C and A.

**Comment by simontoens** [comment]
Actually a concrete issue here is that if a change to C breaks B (and B is not imported), then we do not show any error.

**Comment by simontoens** [comment]
@plaird I think for the A -> B -> C scenario where only A and C are imported, but a change in C causes B to not build (B gets build because it is a dep of A), we can just show a somewhat generic, but informative error message, such as "build error in project that is not imported: ..."
I will make that change.

**Comment by plaird** [comment]
Thanks for fixing this Simon.
